apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod
  labels:
    app: myapp
spec:
  containers:
    - name: nginx-containers
    # specify the image name we want to use 
      image: nginx 

# To create a pod use the following command
# `kubectl create -f pod-definition.yaml`