apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  # we are creating a Node port here
  type: NodePort
  ports:
    - port: 80 # port on service
      targetPort: 80 # port at whcih nginx listens
      nodePort: 30004 # node port (minikube node) whcih we can use to access the nginx
  selector: # whcih pods this service should select
    app: myapp

# the commands for running this can be found at services.md
